apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: DATA+OMITTED
    server: https://k8spratice-dns-damp208a.hcp.eastus.azmk8s.io:443
  name: k8spratice
contexts:
- context:
    cluster: k8spratice
    user: clusterUser_CLG-HDP-DGCT_k8spratice
  name: k8spratice
current-context: k8spratice
kind: Config
preferences: {}
users:
- name: clusterUser_CLG-HDP-DGCT_k8spratice
  user:
    client-certificate-data: DATA+OMITTED
    client-key-data: DATA+OMITTED
    token: REDACTED
