apiVersion: apps/v1
kind: Deployment
metadata:
  name: adservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: adservice
  template:
    metadata:
      labels:
        app: adservice
    spec:
      containers:
        - name: server
          image: "k8scontainerpratice.azurecr.io/adservice:latest"
          ports:
            - containerPort: 9555

---
apiVersion: v1
kind: Service
metadata:
  name: adservice
  namespace: nonprod
spec:
  type: ClusterIP
  selector:
    app: adservice
  ports:
    - name: http
      port: 9555
      targetPort: 9555

