apiVersion: apps/v1
kind: Deployment
metadata:
  name: currencyservice
  labels:
    app: currencyservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: currencyservice
  template:
    metadata:
      labels:
        app: currencyservice
  spec:
    containers:
      - name: currencyservice
        image: <ACR Name>.azurecr.io/currencyservice:v1
        ports:
          - containerPort: 7000

---
apiVersion: v1
kind: Service
metadata:
  name: currencyservice
spec:
  type: ClusterIP
  selector:
    app: currencyservice
  ports:
    - name: http
      port: 7000
      targetPort: 7000
