apiVersion: apps/v1
kind: Deployment
metadata:
  name: emailservice
  labels:
    app: emailservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: emailservice
  template:
    metadata:
      labels:
        app: emailservice
  spec:
    containers:
      - name: server
        image: <ACR Name>.azurecr.io/emailservice:v1
        ports:
          - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: emailservice
spec:
  type: ClusterIP
  selector:
    app: emailservice
  ports:
    - name: http
      port: 5000
      targetPort: 8080
