
name: Build to AKS

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
  
    - name: Login to ACR
      uses: azure/docker-login@v1
      with:
        login-server: k8scontainerpratice.azurecr.io
        username: ${{ secrets.ACR_USERNAME }}
        password: ${{ secrets.ACR_PASSWORD }}

    - name: Build and push Docker images
      run: |
          docker build -t k8scontainerpratice.azurecr.io/paymentservice-prod:latest ./src/paymentservice
          docker push $ACR_NAME.k8scontainerpratice.azurecr.io/paymentservice-prod:latest"
