
name: Build to AKS - Frontend

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
  
    - name: Login to ACR
      uses: azure/docker-login@v1
      with:
        login-server: k8scontainerregistry1.azurecr.io
        username: ${{ secrets.ACR_USERNAME }}
        password: ${{ secrets.ACR_PASSWORD }}

    - name: Build and push Docker images
      run: |
          cd KubernetesDeployment-Dev/src/frontend
          docker build -t k8scontainerregistry1.azurecr.io/frontend:latest .
          docker push k8scontainerregistry1.azurecr.io/frontend:latest
          
    - name: Deploy to AKS
      uses: azure/k8s-set-context@v1
      with:
        method: kubeconfig
        kubeconfig: ${{ secrets.KUBECONFIG }}

    - name: Apply Kubernetes manifests
      run: |
        cd KubernetesDeployment-Dev/kubernetes/Manifest/
        kubectl apply -f frontend.yaml
